### ISSUE TITLE
askStockfishForBestMove crashs when it cant find bestmove

### ISSUE THREAD

**Issue by JimWest** [macio-gmbh/chess_ar#9]
askStockfishForBestMove crashs here cause he can't find bestmove and pos is 54964894151 so substr crashs.

Better try catch or sth and return empty string

askStockfishForBestMove(const char* fen) {
...
std::size_t pos = res.find("bestmove");
res = res.substr (pos);

**Comment by wili91** [comment]
Should  be fixed now. Forgot to check for string npos after res.find("bestmove");
